# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: so-called programmer
email: sean.cuevo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My personal blog about web development, mainly Salesforce related.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://seanpat09.github.io" # the base hostname & protocol for your site
twitter_username: squizzleflip
github_username:  seanpat09

# Build settings
markdown: kramdown